name: download
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - pandas=2.2
  - scanpy=1.10
  - psycopg2-binary=2.9
  - pypika=0.48
  - python-dotenv=1.0
  - google-cloud-secret-manager=2.22
  - tiledb==2.27.0
  - tiledbsoma-py==1.15.4
